services:
  db:
    container_name: kindergarden-db
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: kinder_dev
      POSTGRES_PASSWORD: kinder_dev
      POSTGRES_DB: kindergarden
    ports:
      - "5432:5432"
    volumes:
      - ./kindergarden-data:/var/lib/postgresql
    networks:
      - kindergarden

  backend:
    container_name: kindergarden-backend-dev
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    env_file:
      - .env
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/kindergarden
      QUARKUS_PROFILE: dev
      QUARKUS_TELEMETRY_DISABLED: true
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/usr/app
      - "${HOME}/.m2:/root/.m2"
    depends_on:
      - db
    networks:
      - kindergarden

networks:
  kindergarden:
